// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: robot_data.proto

// Protobuf Java Version: 3.25.5
package org.firstinspires.ftc.teamcode.data.protocol;

/**
 * <pre>
 * Protocol version 2 replaces the debug JSON transport with protobuf. The
 * length prefix belongs to the TCP transport, not to this message.
 * </pre>
 *
 * Protobuf type {@code ftc.robotdata.v2.Envelope}
 */
public  final class Envelope extends
    com.google.protobuf.GeneratedMessageLite<
        Envelope, Envelope.Builder> implements
    // @@protoc_insertion_point(message_implements:ftc.robotdata.v2.Envelope)
    EnvelopeOrBuilder {
  private Envelope() {
    sessionId_ = com.google.protobuf.ByteString.EMPTY;
    connectionId_ = com.google.protobuf.ByteString.EMPTY;
  }
  private int bodyCase_ = 0;
  private java.lang.Object body_;
  public enum BodyCase {
    HELLO(10),
    HELLO_ACK(11),
    SCHEMA(12),
    SAMPLE_BATCH(13),
    EVENT(14),
    HEARTBEAT(15),
    GAP(16),
    SESSION_END(17),
    GAMEPAD(18),
    ERROR(19),
    BODY_NOT_SET(0);
    private final int value;
    private BodyCase(int value) {
      this.value = value;
    }
    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static BodyCase valueOf(int value) {
      return forNumber(value);
    }

    public static BodyCase forNumber(int value) {
      switch (value) {
        case 10: return HELLO;
        case 11: return HELLO_ACK;
        case 12: return SCHEMA;
        case 13: return SAMPLE_BATCH;
        case 14: return EVENT;
        case 15: return HEARTBEAT;
        case 16: return GAP;
        case 17: return SESSION_END;
        case 18: return GAMEPAD;
        case 19: return ERROR;
        case 0: return BODY_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  @java.lang.Override
  public BodyCase
  getBodyCase() {
    return BodyCase.forNumber(
        bodyCase_);
  }

  private void clearBody() {
    bodyCase_ = 0;
    body_ = null;
  }

  public static final int PROTOCOL_VERSION_FIELD_NUMBER = 1;
  private int protocolVersion_;
  /**
   * <code>uint32 protocol_version = 1;</code>
   * @return The protocolVersion.
   */
  @java.lang.Override
  public int getProtocolVersion() {
    return protocolVersion_;
  }
  /**
   * <code>uint32 protocol_version = 1;</code>
   * @param value The protocolVersion to set.
   */
  private void setProtocolVersion(int value) {
    
    protocolVersion_ = value;
  }
  /**
   * <code>uint32 protocol_version = 1;</code>
   */
  private void clearProtocolVersion() {

    protocolVersion_ = 0;
  }

  public static final int SESSION_ID_FIELD_NUMBER = 2;
  private com.google.protobuf.ByteString sessionId_;
  /**
   * <pre>
   * 16-byte RFC 4122 UUID
   * </pre>
   *
   * <code>bytes session_id = 2;</code>
   * @return The sessionId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getSessionId() {
    return sessionId_;
  }
  /**
   * <pre>
   * 16-byte RFC 4122 UUID
   * </pre>
   *
   * <code>bytes session_id = 2;</code>
   * @param value The sessionId to set.
   */
  private void setSessionId(com.google.protobuf.ByteString value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    sessionId_ = value;
  }
  /**
   * <pre>
   * 16-byte RFC 4122 UUID
   * </pre>
   *
   * <code>bytes session_id = 2;</code>
   */
  private void clearSessionId() {

    sessionId_ = getDefaultInstance().getSessionId();
  }

  public static final int CONNECTION_ID_FIELD_NUMBER = 3;
  private com.google.protobuf.ByteString connectionId_;
  /**
   * <pre>
   * 16-byte RFC 4122 UUID
   * </pre>
   *
   * <code>bytes connection_id = 3;</code>
   * @return The connectionId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getConnectionId() {
    return connectionId_;
  }
  /**
   * <pre>
   * 16-byte RFC 4122 UUID
   * </pre>
   *
   * <code>bytes connection_id = 3;</code>
   * @param value The connectionId to set.
   */
  private void setConnectionId(com.google.protobuf.ByteString value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    connectionId_ = value;
  }
  /**
   * <pre>
   * 16-byte RFC 4122 UUID
   * </pre>
   *
   * <code>bytes connection_id = 3;</code>
   */
  private void clearConnectionId() {

    connectionId_ = getDefaultInstance().getConnectionId();
  }

  public static final int CONNECTION_SEQUENCE_FIELD_NUMBER = 4;
  private long connectionSequence_;
  /**
   * <code>uint64 connection_sequence = 4;</code>
   * @return The connectionSequence.
   */
  @java.lang.Override
  public long getConnectionSequence() {
    return connectionSequence_;
  }
  /**
   * <code>uint64 connection_sequence = 4;</code>
   * @param value The connectionSequence to set.
   */
  private void setConnectionSequence(long value) {
    
    connectionSequence_ = value;
  }
  /**
   * <code>uint64 connection_sequence = 4;</code>
   */
  private void clearConnectionSequence() {

    connectionSequence_ = 0L;
  }

  public static final int ROBOT_ELAPSED_NS_FIELD_NUMBER = 5;
  private long robotElapsedNs_;
  /**
   * <code>uint64 robot_elapsed_ns = 5;</code>
   * @return The robotElapsedNs.
   */
  @java.lang.Override
  public long getRobotElapsedNs() {
    return robotElapsedNs_;
  }
  /**
   * <code>uint64 robot_elapsed_ns = 5;</code>
   * @param value The robotElapsedNs to set.
   */
  private void setRobotElapsedNs(long value) {
    
    robotElapsedNs_ = value;
  }
  /**
   * <code>uint64 robot_elapsed_ns = 5;</code>
   */
  private void clearRobotElapsedNs() {

    robotElapsedNs_ = 0L;
  }

  public static final int HELLO_FIELD_NUMBER = 10;
  /**
   * <code>.ftc.robotdata.v2.Hello hello = 10;</code>
   */
  @java.lang.Override
  public boolean hasHello() {
    return bodyCase_ == 10;
  }
  /**
   * <code>.ftc.robotdata.v2.Hello hello = 10;</code>
   */
  @java.lang.Override
  public org.firstinspires.ftc.teamcode.data.protocol.Hello getHello() {
    if (bodyCase_ == 10) {
       return (org.firstinspires.ftc.teamcode.data.protocol.Hello) body_;
    }
    return org.firstinspires.ftc.teamcode.data.protocol.Hello.getDefaultInstance();
  }
  /**
   * <code>.ftc.robotdata.v2.Hello hello = 10;</code>
   */
  private void setHello(org.firstinspires.ftc.teamcode.data.protocol.Hello value) {
    value.getClass();
  body_ = value;
    bodyCase_ = 10;
  }
  /**
   * <code>.ftc.robotdata.v2.Hello hello = 10;</code>
   */
  private void mergeHello(org.firstinspires.ftc.teamcode.data.protocol.Hello value) {
    value.getClass();
  if (bodyCase_ == 10 &&
        body_ != org.firstinspires.ftc.teamcode.data.protocol.Hello.getDefaultInstance()) {
      body_ = org.firstinspires.ftc.teamcode.data.protocol.Hello.newBuilder((org.firstinspires.ftc.teamcode.data.protocol.Hello) body_)
          .mergeFrom(value).buildPartial();
    } else {
      body_ = value;
    }
    bodyCase_ = 10;
  }
  /**
   * <code>.ftc.robotdata.v2.Hello hello = 10;</code>
   */
  private void clearHello() {
    if (bodyCase_ == 10) {
      bodyCase_ = 0;
      body_ = null;
    }
  }

  public static final int HELLO_ACK_FIELD_NUMBER = 11;
  /**
   * <code>.ftc.robotdata.v2.HelloAck hello_ack = 11;</code>
   */
  @java.lang.Override
  public boolean hasHelloAck() {
    return bodyCase_ == 11;
  }
  /**
   * <code>.ftc.robotdata.v2.HelloAck hello_ack = 11;</code>
   */
  @java.lang.Override
  public org.firstinspires.ftc.teamcode.data.protocol.HelloAck getHelloAck() {
    if (bodyCase_ == 11) {
       return (org.firstinspires.ftc.teamcode.data.protocol.HelloAck) body_;
    }
    return org.firstinspires.ftc.teamcode.data.protocol.HelloAck.getDefaultInstance();
  }
  /**
   * <code>.ftc.robotdata.v2.HelloAck hello_ack = 11;</code>
   */
  private void setHelloAck(org.firstinspires.ftc.teamcode.data.protocol.HelloAck value) {
    value.getClass();
  body_ = value;
    bodyCase_ = 11;
  }
  /**
   * <code>.ftc.robotdata.v2.HelloAck hello_ack = 11;</code>
   */
  private void mergeHelloAck(org.firstinspires.ftc.teamcode.data.protocol.HelloAck value) {
    value.getClass();
  if (bodyCase_ == 11 &&
        body_ != org.firstinspires.ftc.teamcode.data.protocol.HelloAck.getDefaultInstance()) {
      body_ = org.firstinspires.ftc.teamcode.data.protocol.HelloAck.newBuilder((org.firstinspires.ftc.teamcode.data.protocol.HelloAck) body_)
          .mergeFrom(value).buildPartial();
    } else {
      body_ = value;
    }
    bodyCase_ = 11;
  }
  /**
   * <code>.ftc.robotdata.v2.HelloAck hello_ack = 11;</code>
   */
  private void clearHelloAck() {
    if (bodyCase_ == 11) {
      bodyCase_ = 0;
      body_ = null;
    }
  }

  public static final int SCHEMA_FIELD_NUMBER = 12;
  /**
   * <code>.ftc.robotdata.v2.Schema schema = 12;</code>
   */
  @java.lang.Override
  public boolean hasSchema() {
    return bodyCase_ == 12;
  }
  /**
   * <code>.ftc.robotdata.v2.Schema schema = 12;</code>
   */
  @java.lang.Override
  public org.firstinspires.ftc.teamcode.data.protocol.Schema getSchema() {
    if (bodyCase_ == 12) {
       return (org.firstinspires.ftc.teamcode.data.protocol.Schema) body_;
    }
    return org.firstinspires.ftc.teamcode.data.protocol.Schema.getDefaultInstance();
  }
  /**
   * <code>.ftc.robotdata.v2.Schema schema = 12;</code>
   */
  private void setSchema(org.firstinspires.ftc.teamcode.data.protocol.Schema value) {
    value.getClass();
  body_ = value;
    bodyCase_ = 12;
  }
  /**
   * <code>.ftc.robotdata.v2.Schema schema = 12;</code>
   */
  private void mergeSchema(org.firstinspires.ftc.teamcode.data.protocol.Schema value) {
    value.getClass();
  if (bodyCase_ == 12 &&
        body_ != org.firstinspires.ftc.teamcode.data.protocol.Schema.getDefaultInstance()) {
      body_ = org.firstinspires.ftc.teamcode.data.protocol.Schema.newBuilder((org.firstinspires.ftc.teamcode.data.protocol.Schema) body_)
          .mergeFrom(value).buildPartial();
    } else {
      body_ = value;
    }
    bodyCase_ = 12;
  }
  /**
   * <code>.ftc.robotdata.v2.Schema schema = 12;</code>
   */
  private void clearSchema() {
    if (bodyCase_ == 12) {
      bodyCase_ = 0;
      body_ = null;
    }
  }

  public static final int SAMPLE_BATCH_FIELD_NUMBER = 13;
  /**
   * <code>.ftc.robotdata.v2.SampleBatch sample_batch = 13;</code>
   */
  @java.lang.Override
  public boolean hasSampleBatch() {
    return bodyCase_ == 13;
  }
  /**
   * <code>.ftc.robotdata.v2.SampleBatch sample_batch = 13;</code>
   */
  @java.lang.Override
  public org.firstinspires.ftc.teamcode.data.protocol.SampleBatch getSampleBatch() {
    if (bodyCase_ == 13) {
       return (org.firstinspires.ftc.teamcode.data.protocol.SampleBatch) body_;
    }
    return org.firstinspires.ftc.teamcode.data.protocol.SampleBatch.getDefaultInstance();
  }
  /**
   * <code>.ftc.robotdata.v2.SampleBatch sample_batch = 13;</code>
   */
  private void setSampleBatch(org.firstinspires.ftc.teamcode.data.protocol.SampleBatch value) {
    value.getClass();
  body_ = value;
    bodyCase_ = 13;
  }
  /**
   * <code>.ftc.robotdata.v2.SampleBatch sample_batch = 13;</code>
   */
  private void mergeSampleBatch(org.firstinspires.ftc.teamcode.data.protocol.SampleBatch value) {
    value.getClass();
  if (bodyCase_ == 13 &&
        body_ != org.firstinspires.ftc.teamcode.data.protocol.SampleBatch.getDefaultInstance()) {
      body_ = org.firstinspires.ftc.teamcode.data.protocol.SampleBatch.newBuilder((org.firstinspires.ftc.teamcode.data.protocol.SampleBatch) body_)
          .mergeFrom(value).buildPartial();
    } else {
      body_ = value;
    }
    bodyCase_ = 13;
  }
  /**
   * <code>.ftc.robotdata.v2.SampleBatch sample_batch = 13;</code>
   */
  private void clearSampleBatch() {
    if (bodyCase_ == 13) {
      bodyCase_ = 0;
      body_ = null;
    }
  }

  public static final int EVENT_FIELD_NUMBER = 14;
  /**
   * <code>.ftc.robotdata.v2.Event event = 14;</code>
   */
  @java.lang.Override
  public boolean hasEvent() {
    return bodyCase_ == 14;
  }
  /**
   * <code>.ftc.robotdata.v2.Event event = 14;</code>
   */
  @java.lang.Override
  public org.firstinspires.ftc.teamcode.data.protocol.Event getEvent() {
    if (bodyCase_ == 14) {
       return (org.firstinspires.ftc.teamcode.data.protocol.Event) body_;
    }
    return org.firstinspires.ftc.teamcode.data.protocol.Event.getDefaultInstance();
  }
  /**
   * <code>.ftc.robotdata.v2.Event event = 14;</code>
   */
  private void setEvent(org.firstinspires.ftc.teamcode.data.protocol.Event value) {
    value.getClass();
  body_ = value;
    bodyCase_ = 14;
  }
  /**
   * <code>.ftc.robotdata.v2.Event event = 14;</code>
   */
  private void mergeEvent(org.firstinspires.ftc.teamcode.data.protocol.Event value) {
    value.getClass();
  if (bodyCase_ == 14 &&
        body_ != org.firstinspires.ftc.teamcode.data.protocol.Event.getDefaultInstance()) {
      body_ = org.firstinspires.ftc.teamcode.data.protocol.Event.newBuilder((org.firstinspires.ftc.teamcode.data.protocol.Event) body_)
          .mergeFrom(value).buildPartial();
    } else {
      body_ = value;
    }
    bodyCase_ = 14;
  }
  /**
   * <code>.ftc.robotdata.v2.Event event = 14;</code>
   */
  private void clearEvent() {
    if (bodyCase_ == 14) {
      bodyCase_ = 0;
      body_ = null;
    }
  }

  public static final int HEARTBEAT_FIELD_NUMBER = 15;
  /**
   * <code>.ftc.robotdata.v2.Heartbeat heartbeat = 15;</code>
   */
  @java.lang.Override
  public boolean hasHeartbeat() {
    return bodyCase_ == 15;
  }
  /**
   * <code>.ftc.robotdata.v2.Heartbeat heartbeat = 15;</code>
   */
  @java.lang.Override
  public org.firstinspires.ftc.teamcode.data.protocol.Heartbeat getHeartbeat() {
    if (bodyCase_ == 15) {
       return (org.firstinspires.ftc.teamcode.data.protocol.Heartbeat) body_;
    }
    return org.firstinspires.ftc.teamcode.data.protocol.Heartbeat.getDefaultInstance();
  }
  /**
   * <code>.ftc.robotdata.v2.Heartbeat heartbeat = 15;</code>
   */
  private void setHeartbeat(org.firstinspires.ftc.teamcode.data.protocol.Heartbeat value) {
    value.getClass();
  body_ = value;
    bodyCase_ = 15;
  }
  /**
   * <code>.ftc.robotdata.v2.Heartbeat heartbeat = 15;</code>
   */
  private void mergeHeartbeat(org.firstinspires.ftc.teamcode.data.protocol.Heartbeat value) {
    value.getClass();
  if (bodyCase_ == 15 &&
        body_ != org.firstinspires.ftc.teamcode.data.protocol.Heartbeat.getDefaultInstance()) {
      body_ = org.firstinspires.ftc.teamcode.data.protocol.Heartbeat.newBuilder((org.firstinspires.ftc.teamcode.data.protocol.Heartbeat) body_)
          .mergeFrom(value).buildPartial();
    } else {
      body_ = value;
    }
    bodyCase_ = 15;
  }
  /**
   * <code>.ftc.robotdata.v2.Heartbeat heartbeat = 15;</code>
   */
  private void clearHeartbeat() {
    if (bodyCase_ == 15) {
      bodyCase_ = 0;
      body_ = null;
    }
  }

  public static final int GAP_FIELD_NUMBER = 16;
  /**
   * <code>.ftc.robotdata.v2.Gap gap = 16;</code>
   */
  @java.lang.Override
  public boolean hasGap() {
    return bodyCase_ == 16;
  }
  /**
   * <code>.ftc.robotdata.v2.Gap gap = 16;</code>
   */
  @java.lang.Override
  public org.firstinspires.ftc.teamcode.data.protocol.Gap getGap() {
    if (bodyCase_ == 16) {
       return (org.firstinspires.ftc.teamcode.data.protocol.Gap) body_;
    }
    return org.firstinspires.ftc.teamcode.data.protocol.Gap.getDefaultInstance();
  }
  /**
   * <code>.ftc.robotdata.v2.Gap gap = 16;</code>
   */
  private void setGap(org.firstinspires.ftc.teamcode.data.protocol.Gap value) {
    value.getClass();
  body_ = value;
    bodyCase_ = 16;
  }
  /**
   * <code>.ftc.robotdata.v2.Gap gap = 16;</code>
   */
  private void mergeGap(org.firstinspires.ftc.teamcode.data.protocol.Gap value) {
    value.getClass();
  if (bodyCase_ == 16 &&
        body_ != org.firstinspires.ftc.teamcode.data.protocol.Gap.getDefaultInstance()) {
      body_ = org.firstinspires.ftc.teamcode.data.protocol.Gap.newBuilder((org.firstinspires.ftc.teamcode.data.protocol.Gap) body_)
          .mergeFrom(value).buildPartial();
    } else {
      body_ = value;
    }
    bodyCase_ = 16;
  }
  /**
   * <code>.ftc.robotdata.v2.Gap gap = 16;</code>
   */
  private void clearGap() {
    if (bodyCase_ == 16) {
      bodyCase_ = 0;
      body_ = null;
    }
  }

  public static final int SESSION_END_FIELD_NUMBER = 17;
  /**
   * <code>.ftc.robotdata.v2.SessionEnd session_end = 17;</code>
   */
  @java.lang.Override
  public boolean hasSessionEnd() {
    return bodyCase_ == 17;
  }
  /**
   * <code>.ftc.robotdata.v2.SessionEnd session_end = 17;</code>
   */
  @java.lang.Override
  public org.firstinspires.ftc.teamcode.data.protocol.SessionEnd getSessionEnd() {
    if (bodyCase_ == 17) {
       return (org.firstinspires.ftc.teamcode.data.protocol.SessionEnd) body_;
    }
    return org.firstinspires.ftc.teamcode.data.protocol.SessionEnd.getDefaultInstance();
  }
  /**
   * <code>.ftc.robotdata.v2.SessionEnd session_end = 17;</code>
   */
  private void setSessionEnd(org.firstinspires.ftc.teamcode.data.protocol.SessionEnd value) {
    value.getClass();
  body_ = value;
    bodyCase_ = 17;
  }
  /**
   * <code>.ftc.robotdata.v2.SessionEnd session_end = 17;</code>
   */
  private void mergeSessionEnd(org.firstinspires.ftc.teamcode.data.protocol.SessionEnd value) {
    value.getClass();
  if (bodyCase_ == 17 &&
        body_ != org.firstinspires.ftc.teamcode.data.protocol.SessionEnd.getDefaultInstance()) {
      body_ = org.firstinspires.ftc.teamcode.data.protocol.SessionEnd.newBuilder((org.firstinspires.ftc.teamcode.data.protocol.SessionEnd) body_)
          .mergeFrom(value).buildPartial();
    } else {
      body_ = value;
    }
    bodyCase_ = 17;
  }
  /**
   * <code>.ftc.robotdata.v2.SessionEnd session_end = 17;</code>
   */
  private void clearSessionEnd() {
    if (bodyCase_ == 17) {
      bodyCase_ = 0;
      body_ = null;
    }
  }

  public static final int GAMEPAD_FIELD_NUMBER = 18;
  /**
   * <code>.ftc.robotdata.v2.GamepadSnapshot gamepad = 18;</code>
   */
  @java.lang.Override
  public boolean hasGamepad() {
    return bodyCase_ == 18;
  }
  /**
   * <code>.ftc.robotdata.v2.GamepadSnapshot gamepad = 18;</code>
   */
  @java.lang.Override
  public org.firstinspires.ftc.teamcode.data.protocol.GamepadSnapshot getGamepad() {
    if (bodyCase_ == 18) {
       return (org.firstinspires.ftc.teamcode.data.protocol.GamepadSnapshot) body_;
    }
    return org.firstinspires.ftc.teamcode.data.protocol.GamepadSnapshot.getDefaultInstance();
  }
  /**
   * <code>.ftc.robotdata.v2.GamepadSnapshot gamepad = 18;</code>
   */
  private void setGamepad(org.firstinspires.ftc.teamcode.data.protocol.GamepadSnapshot value) {
    value.getClass();
  body_ = value;
    bodyCase_ = 18;
  }
  /**
   * <code>.ftc.robotdata.v2.GamepadSnapshot gamepad = 18;</code>
   */
  private void mergeGamepad(org.firstinspires.ftc.teamcode.data.protocol.GamepadSnapshot value) {
    value.getClass();
  if (bodyCase_ == 18 &&
        body_ != org.firstinspires.ftc.teamcode.data.protocol.GamepadSnapshot.getDefaultInstance()) {
      body_ = org.firstinspires.ftc.teamcode.data.protocol.GamepadSnapshot.newBuilder((org.firstinspires.ftc.teamcode.data.protocol.GamepadSnapshot) body_)
          .mergeFrom(value).buildPartial();
    } else {
      body_ = value;
    }
    bodyCase_ = 18;
  }
  /**
   * <code>.ftc.robotdata.v2.GamepadSnapshot gamepad = 18;</code>
   */
  private void clearGamepad() {
    if (bodyCase_ == 18) {
      bodyCase_ = 0;
      body_ = null;
    }
  }

  public static final int ERROR_FIELD_NUMBER = 19;
  /**
   * <code>.ftc.robotdata.v2.ProtocolError error = 19;</code>
   */
  @java.lang.Override
  public boolean hasError() {
    return bodyCase_ == 19;
  }
  /**
   * <code>.ftc.robotdata.v2.ProtocolError error = 19;</code>
   */
  @java.lang.Override
  public org.firstinspires.ftc.teamcode.data.protocol.ProtocolError getError() {
    if (bodyCase_ == 19) {
       return (org.firstinspires.ftc.teamcode.data.protocol.ProtocolError) body_;
    }
    return org.firstinspires.ftc.teamcode.data.protocol.ProtocolError.getDefaultInstance();
  }
  /**
   * <code>.ftc.robotdata.v2.ProtocolError error = 19;</code>
   */
  private void setError(org.firstinspires.ftc.teamcode.data.protocol.ProtocolError value) {
    value.getClass();
  body_ = value;
    bodyCase_ = 19;
  }
  /**
   * <code>.ftc.robotdata.v2.ProtocolError error = 19;</code>
   */
  private void mergeError(org.firstinspires.ftc.teamcode.data.protocol.ProtocolError value) {
    value.getClass();
  if (bodyCase_ == 19 &&
        body_ != org.firstinspires.ftc.teamcode.data.protocol.ProtocolError.getDefaultInstance()) {
      body_ = org.firstinspires.ftc.teamcode.data.protocol.ProtocolError.newBuilder((org.firstinspires.ftc.teamcode.data.protocol.ProtocolError) body_)
          .mergeFrom(value).buildPartial();
    } else {
      body_ = value;
    }
    bodyCase_ = 19;
  }
  /**
   * <code>.ftc.robotdata.v2.ProtocolError error = 19;</code>
   */
  private void clearError() {
    if (bodyCase_ == 19) {
      bodyCase_ = 0;
      body_ = null;
    }
  }

  public static org.firstinspires.ftc.teamcode.data.protocol.Envelope parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static org.firstinspires.ftc.teamcode.data.protocol.Envelope parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static org.firstinspires.ftc.teamcode.data.protocol.Envelope parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static org.firstinspires.ftc.teamcode.data.protocol.Envelope parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static org.firstinspires.ftc.teamcode.data.protocol.Envelope parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static org.firstinspires.ftc.teamcode.data.protocol.Envelope parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static org.firstinspires.ftc.teamcode.data.protocol.Envelope parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static org.firstinspires.ftc.teamcode.data.protocol.Envelope parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static org.firstinspires.ftc.teamcode.data.protocol.Envelope parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static org.firstinspires.ftc.teamcode.data.protocol.Envelope parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static org.firstinspires.ftc.teamcode.data.protocol.Envelope parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static org.firstinspires.ftc.teamcode.data.protocol.Envelope parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(org.firstinspires.ftc.teamcode.data.protocol.Envelope prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * <pre>
   * Protocol version 2 replaces the debug JSON transport with protobuf. The
   * length prefix belongs to the TCP transport, not to this message.
   * </pre>
   *
   * Protobuf type {@code ftc.robotdata.v2.Envelope}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        org.firstinspires.ftc.teamcode.data.protocol.Envelope, Builder> implements
      // @@protoc_insertion_point(builder_implements:ftc.robotdata.v2.Envelope)
      org.firstinspires.ftc.teamcode.data.protocol.EnvelopeOrBuilder {
    // Construct using org.firstinspires.ftc.teamcode.data.protocol.Envelope.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }

    @java.lang.Override
    public BodyCase
        getBodyCase() {
      return instance.getBodyCase();
    }

    public Builder clearBody() {
      copyOnWrite();
      instance.clearBody();
      return this;
    }


    /**
     * <code>uint32 protocol_version = 1;</code>
     * @return The protocolVersion.
     */
    @java.lang.Override
    public int getProtocolVersion() {
      return instance.getProtocolVersion();
    }
    /**
     * <code>uint32 protocol_version = 1;</code>
     * @param value The protocolVersion to set.
     * @return This builder for chaining.
     */
    public Builder setProtocolVersion(int value) {
      copyOnWrite();
      instance.setProtocolVersion(value);
      return this;
    }
    /**
     * <code>uint32 protocol_version = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearProtocolVersion() {
      copyOnWrite();
      instance.clearProtocolVersion();
      return this;
    }

    /**
     * <pre>
     * 16-byte RFC 4122 UUID
     * </pre>
     *
     * <code>bytes session_id = 2;</code>
     * @return The sessionId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getSessionId() {
      return instance.getSessionId();
    }
    /**
     * <pre>
     * 16-byte RFC 4122 UUID
     * </pre>
     *
     * <code>bytes session_id = 2;</code>
     * @param value The sessionId to set.
     * @return This builder for chaining.
     */
    public Builder setSessionId(com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setSessionId(value);
      return this;
    }
    /**
     * <pre>
     * 16-byte RFC 4122 UUID
     * </pre>
     *
     * <code>bytes session_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearSessionId() {
      copyOnWrite();
      instance.clearSessionId();
      return this;
    }

    /**
     * <pre>
     * 16-byte RFC 4122 UUID
     * </pre>
     *
     * <code>bytes connection_id = 3;</code>
     * @return The connectionId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getConnectionId() {
      return instance.getConnectionId();
    }
    /**
     * <pre>
     * 16-byte RFC 4122 UUID
     * </pre>
     *
     * <code>bytes connection_id = 3;</code>
     * @param value The connectionId to set.
     * @return This builder for chaining.
     */
    public Builder setConnectionId(com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setConnectionId(value);
      return this;
    }
    /**
     * <pre>
     * 16-byte RFC 4122 UUID
     * </pre>
     *
     * <code>bytes connection_id = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearConnectionId() {
      copyOnWrite();
      instance.clearConnectionId();
      return this;
    }

    /**
     * <code>uint64 connection_sequence = 4;</code>
     * @return The connectionSequence.
     */
    @java.lang.Override
    public long getConnectionSequence() {
      return instance.getConnectionSequence();
    }
    /**
     * <code>uint64 connection_sequence = 4;</code>
     * @param value The connectionSequence to set.
     * @return This builder for chaining.
     */
    public Builder setConnectionSequence(long value) {
      copyOnWrite();
      instance.setConnectionSequence(value);
      return this;
    }
    /**
     * <code>uint64 connection_sequence = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearConnectionSequence() {
      copyOnWrite();
      instance.clearConnectionSequence();
      return this;
    }

    /**
     * <code>uint64 robot_elapsed_ns = 5;</code>
     * @return The robotElapsedNs.
     */
    @java.lang.Override
    public long getRobotElapsedNs() {
      return instance.getRobotElapsedNs();
    }
    /**
     * <code>uint64 robot_elapsed_ns = 5;</code>
     * @param value The robotElapsedNs to set.
     * @return This builder for chaining.
     */
    public Builder setRobotElapsedNs(long value) {
      copyOnWrite();
      instance.setRobotElapsedNs(value);
      return this;
    }
    /**
     * <code>uint64 robot_elapsed_ns = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearRobotElapsedNs() {
      copyOnWrite();
      instance.clearRobotElapsedNs();
      return this;
    }

    /**
     * <code>.ftc.robotdata.v2.Hello hello = 10;</code>
     */
    @java.lang.Override
    public boolean hasHello() {
      return instance.hasHello();
    }
    /**
     * <code>.ftc.robotdata.v2.Hello hello = 10;</code>
     */
    @java.lang.Override
    public org.firstinspires.ftc.teamcode.data.protocol.Hello getHello() {
      return instance.getHello();
    }
    /**
     * <code>.ftc.robotdata.v2.Hello hello = 10;</code>
     */
    public Builder setHello(org.firstinspires.ftc.teamcode.data.protocol.Hello value) {
      copyOnWrite();
      instance.setHello(value);
      return this;
    }
    /**
     * <code>.ftc.robotdata.v2.Hello hello = 10;</code>
     */
    public Builder setHello(
        org.firstinspires.ftc.teamcode.data.protocol.Hello.Builder builderForValue) {
      copyOnWrite();
      instance.setHello(builderForValue.build());
      return this;
    }
    /**
     * <code>.ftc.robotdata.v2.Hello hello = 10;</code>
     */
    public Builder mergeHello(org.firstinspires.ftc.teamcode.data.protocol.Hello value) {
      copyOnWrite();
      instance.mergeHello(value);
      return this;
    }
    /**
     * <code>.ftc.robotdata.v2.Hello hello = 10;</code>
     */
    public Builder clearHello() {
      copyOnWrite();
      instance.clearHello();
      return this;
    }

    /**
     * <code>.ftc.robotdata.v2.HelloAck hello_ack = 11;</code>
     */
    @java.lang.Override
    public boolean hasHelloAck() {
      return instance.hasHelloAck();
    }
    /**
     * <code>.ftc.robotdata.v2.HelloAck hello_ack = 11;</code>
     */
    @java.lang.Override
    public org.firstinspires.ftc.teamcode.data.protocol.HelloAck getHelloAck() {
      return instance.getHelloAck();
    }
    /**
     * <code>.ftc.robotdata.v2.HelloAck hello_ack = 11;</code>
     */
    public Builder setHelloAck(org.firstinspires.ftc.teamcode.data.protocol.HelloAck value) {
      copyOnWrite();
      instance.setHelloAck(value);
      return this;
    }
    /**
     * <code>.ftc.robotdata.v2.HelloAck hello_ack = 11;</code>
     */
    public Builder setHelloAck(
        org.firstinspires.ftc.teamcode.data.protocol.HelloAck.Builder builderForValue) {
      copyOnWrite();
      instance.setHelloAck(builderForValue.build());
      return this;
    }
    /**
     * <code>.ftc.robotdata.v2.HelloAck hello_ack = 11;</code>
     */
    public Builder mergeHelloAck(org.firstinspires.ftc.teamcode.data.protocol.HelloAck value) {
      copyOnWrite();
      instance.mergeHelloAck(value);
      return this;
    }
    /**
     * <code>.ftc.robotdata.v2.HelloAck hello_ack = 11;</code>
     */
    public Builder clearHelloAck() {
      copyOnWrite();
      instance.clearHelloAck();
      return this;
    }

    /**
     * <code>.ftc.robotdata.v2.Schema schema = 12;</code>
     */
    @java.lang.Override
    public boolean hasSchema() {
      return instance.hasSchema();
    }
    /**
     * <code>.ftc.robotdata.v2.Schema schema = 12;</code>
     */
    @java.lang.Override
    public org.firstinspires.ftc.teamcode.data.protocol.Schema getSchema() {
      return instance.getSchema();
    }
    /**
     * <code>.ftc.robotdata.v2.Schema schema = 12;</code>
     */
    public Builder setSchema(org.firstinspires.ftc.teamcode.data.protocol.Schema value) {
      copyOnWrite();
      instance.setSchema(value);
      return this;
    }
    /**
     * <code>.ftc.robotdata.v2.Schema schema = 12;</code>
     */
    public Builder setSchema(
        org.firstinspires.ftc.teamcode.data.protocol.Schema.Builder builderForValue) {
      copyOnWrite();
      instance.setSchema(builderForValue.build());
      return this;
    }
    /**
     * <code>.ftc.robotdata.v2.Schema schema = 12;</code>
     */
    public Builder mergeSchema(org.firstinspires.ftc.teamcode.data.protocol.Schema value) {
      copyOnWrite();
      instance.mergeSchema(value);
      return this;
    }
    /**
     * <code>.ftc.robotdata.v2.Schema schema = 12;</code>
     */
    public Builder clearSchema() {
      copyOnWrite();
      instance.clearSchema();
      return this;
    }

    /**
     * <code>.ftc.robotdata.v2.SampleBatch sample_batch = 13;</code>
     */
    @java.lang.Override
    public boolean hasSampleBatch() {
      return instance.hasSampleBatch();
    }
    /**
     * <code>.ftc.robotdata.v2.SampleBatch sample_batch = 13;</code>
     */
    @java.lang.Override
    public org.firstinspires.ftc.teamcode.data.protocol.SampleBatch getSampleBatch() {
      return instance.getSampleBatch();
    }
    /**
     * <code>.ftc.robotdata.v2.SampleBatch sample_batch = 13;</code>
     */
    public Builder setSampleBatch(org.firstinspires.ftc.teamcode.data.protocol.SampleBatch value) {
      copyOnWrite();
      instance.setSampleBatch(value);
      return this;
    }
    /**
     * <code>.ftc.robotdata.v2.SampleBatch sample_batch = 13;</code>
     */
    public Builder setSampleBatch(
        org.firstinspires.ftc.teamcode.data.protocol.SampleBatch.Builder builderForValue) {
      copyOnWrite();
      instance.setSampleBatch(builderForValue.build());
      return this;
    }
    /**
     * <code>.ftc.robotdata.v2.SampleBatch sample_batch = 13;</code>
     */
    public Builder mergeSampleBatch(org.firstinspires.ftc.teamcode.data.protocol.SampleBatch value) {
      copyOnWrite();
      instance.mergeSampleBatch(value);
      return this;
    }
    /**
     * <code>.ftc.robotdata.v2.SampleBatch sample_batch = 13;</code>
     */
    public Builder clearSampleBatch() {
      copyOnWrite();
      instance.clearSampleBatch();
      return this;
    }

    /**
     * <code>.ftc.robotdata.v2.Event event = 14;</code>
     */
    @java.lang.Override
    public boolean hasEvent() {
      return instance.hasEvent();
    }
    /**
     * <code>.ftc.robotdata.v2.Event event = 14;</code>
     */
    @java.lang.Override
    public org.firstinspires.ftc.teamcode.data.protocol.Event getEvent() {
      return instance.getEvent();
    }
    /**
     * <code>.ftc.robotdata.v2.Event event = 14;</code>
     */
    public Builder setEvent(org.firstinspires.ftc.teamcode.data.protocol.Event value) {
      copyOnWrite();
      instance.setEvent(value);
      return this;
    }
    /**
     * <code>.ftc.robotdata.v2.Event event = 14;</code>
     */
    public Builder setEvent(
        org.firstinspires.ftc.teamcode.data.protocol.Event.Builder builderForValue) {
      copyOnWrite();
      instance.setEvent(builderForValue.build());
      return this;
    }
    /**
     * <code>.ftc.robotdata.v2.Event event = 14;</code>
     */
    public Builder mergeEvent(org.firstinspires.ftc.teamcode.data.protocol.Event value) {
      copyOnWrite();
      instance.mergeEvent(value);
      return this;
    }
    /**
     * <code>.ftc.robotdata.v2.Event event = 14;</code>
     */
    public Builder clearEvent() {
      copyOnWrite();
      instance.clearEvent();
      return this;
    }

    /**
     * <code>.ftc.robotdata.v2.Heartbeat heartbeat = 15;</code>
     */
    @java.lang.Override
    public boolean hasHeartbeat() {
      return instance.hasHeartbeat();
    }
    /**
     * <code>.ftc.robotdata.v2.Heartbeat heartbeat = 15;</code>
     */
    @java.lang.Override
    public org.firstinspires.ftc.teamcode.data.protocol.Heartbeat getHeartbeat() {
      return instance.getHeartbeat();
    }
    /**
     * <code>.ftc.robotdata.v2.Heartbeat heartbeat = 15;</code>
     */
    public Builder setHeartbeat(org.firstinspires.ftc.teamcode.data.protocol.Heartbeat value) {
      copyOnWrite();
      instance.setHeartbeat(value);
      return this;
    }
    /**
     * <code>.ftc.robotdata.v2.Heartbeat heartbeat = 15;</code>
     */
    public Builder setHeartbeat(
        org.firstinspires.ftc.teamcode.data.protocol.Heartbeat.Builder builderForValue) {
      copyOnWrite();
      instance.setHeartbeat(builderForValue.build());
      return this;
    }
    /**
     * <code>.ftc.robotdata.v2.Heartbeat heartbeat = 15;</code>
     */
    public Builder mergeHeartbeat(org.firstinspires.ftc.teamcode.data.protocol.Heartbeat value) {
      copyOnWrite();
      instance.mergeHeartbeat(value);
      return this;
    }
    /**
     * <code>.ftc.robotdata.v2.Heartbeat heartbeat = 15;</code>
     */
    public Builder clearHeartbeat() {
      copyOnWrite();
      instance.clearHeartbeat();
      return this;
    }

    /**
     * <code>.ftc.robotdata.v2.Gap gap = 16;</code>
     */
    @java.lang.Override
    public boolean hasGap() {
      return instance.hasGap();
    }
    /**
     * <code>.ftc.robotdata.v2.Gap gap = 16;</code>
     */
    @java.lang.Override
    public org.firstinspires.ftc.teamcode.data.protocol.Gap getGap() {
      return instance.getGap();
    }
    /**
     * <code>.ftc.robotdata.v2.Gap gap = 16;</code>
     */
    public Builder setGap(org.firstinspires.ftc.teamcode.data.protocol.Gap value) {
      copyOnWrite();
      instance.setGap(value);
      return this;
    }
    /**
     * <code>.ftc.robotdata.v2.Gap gap = 16;</code>
     */
    public Builder setGap(
        org.firstinspires.ftc.teamcode.data.protocol.Gap.Builder builderForValue) {
      copyOnWrite();
      instance.setGap(builderForValue.build());
      return this;
    }
    /**
     * <code>.ftc.robotdata.v2.Gap gap = 16;</code>
     */
    public Builder mergeGap(org.firstinspires.ftc.teamcode.data.protocol.Gap value) {
      copyOnWrite();
      instance.mergeGap(value);
      return this;
    }
    /**
     * <code>.ftc.robotdata.v2.Gap gap = 16;</code>
     */
    public Builder clearGap() {
      copyOnWrite();
      instance.clearGap();
      return this;
    }

    /**
     * <code>.ftc.robotdata.v2.SessionEnd session_end = 17;</code>
     */
    @java.lang.Override
    public boolean hasSessionEnd() {
      return instance.hasSessionEnd();
    }
    /**
     * <code>.ftc.robotdata.v2.SessionEnd session_end = 17;</code>
     */
    @java.lang.Override
    public org.firstinspires.ftc.teamcode.data.protocol.SessionEnd getSessionEnd() {
      return instance.getSessionEnd();
    }
    /**
     * <code>.ftc.robotdata.v2.SessionEnd session_end = 17;</code>
     */
    public Builder setSessionEnd(org.firstinspires.ftc.teamcode.data.protocol.SessionEnd value) {
      copyOnWrite();
      instance.setSessionEnd(value);
      return this;
    }
    /**
     * <code>.ftc.robotdata.v2.SessionEnd session_end = 17;</code>
     */
    public Builder setSessionEnd(
        org.firstinspires.ftc.teamcode.data.protocol.SessionEnd.Builder builderForValue) {
      copyOnWrite();
      instance.setSessionEnd(builderForValue.build());
      return this;
    }
    /**
     * <code>.ftc.robotdata.v2.SessionEnd session_end = 17;</code>
     */
    public Builder mergeSessionEnd(org.firstinspires.ftc.teamcode.data.protocol.SessionEnd value) {
      copyOnWrite();
      instance.mergeSessionEnd(value);
      return this;
    }
    /**
     * <code>.ftc.robotdata.v2.SessionEnd session_end = 17;</code>
     */
    public Builder clearSessionEnd() {
      copyOnWrite();
      instance.clearSessionEnd();
      return this;
    }

    /**
     * <code>.ftc.robotdata.v2.GamepadSnapshot gamepad = 18;</code>
     */
    @java.lang.Override
    public boolean hasGamepad() {
      return instance.hasGamepad();
    }
    /**
     * <code>.ftc.robotdata.v2.GamepadSnapshot gamepad = 18;</code>
     */
    @java.lang.Override
    public org.firstinspires.ftc.teamcode.data.protocol.GamepadSnapshot getGamepad() {
      return instance.getGamepad();
    }
    /**
     * <code>.ftc.robotdata.v2.GamepadSnapshot gamepad = 18;</code>
     */
    public Builder setGamepad(org.firstinspires.ftc.teamcode.data.protocol.GamepadSnapshot value) {
      copyOnWrite();
      instance.setGamepad(value);
      return this;
    }
    /**
     * <code>.ftc.robotdata.v2.GamepadSnapshot gamepad = 18;</code>
     */
    public Builder setGamepad(
        org.firstinspires.ftc.teamcode.data.protocol.GamepadSnapshot.Builder builderForValue) {
      copyOnWrite();
      instance.setGamepad(builderForValue.build());
      return this;
    }
    /**
     * <code>.ftc.robotdata.v2.GamepadSnapshot gamepad = 18;</code>
     */
    public Builder mergeGamepad(org.firstinspires.ftc.teamcode.data.protocol.GamepadSnapshot value) {
      copyOnWrite();
      instance.mergeGamepad(value);
      return this;
    }
    /**
     * <code>.ftc.robotdata.v2.GamepadSnapshot gamepad = 18;</code>
     */
    public Builder clearGamepad() {
      copyOnWrite();
      instance.clearGamepad();
      return this;
    }

    /**
     * <code>.ftc.robotdata.v2.ProtocolError error = 19;</code>
     */
    @java.lang.Override
    public boolean hasError() {
      return instance.hasError();
    }
    /**
     * <code>.ftc.robotdata.v2.ProtocolError error = 19;</code>
     */
    @java.lang.Override
    public org.firstinspires.ftc.teamcode.data.protocol.ProtocolError getError() {
      return instance.getError();
    }
    /**
     * <code>.ftc.robotdata.v2.ProtocolError error = 19;</code>
     */
    public Builder setError(org.firstinspires.ftc.teamcode.data.protocol.ProtocolError value) {
      copyOnWrite();
      instance.setError(value);
      return this;
    }
    /**
     * <code>.ftc.robotdata.v2.ProtocolError error = 19;</code>
     */
    public Builder setError(
        org.firstinspires.ftc.teamcode.data.protocol.ProtocolError.Builder builderForValue) {
      copyOnWrite();
      instance.setError(builderForValue.build());
      return this;
    }
    /**
     * <code>.ftc.robotdata.v2.ProtocolError error = 19;</code>
     */
    public Builder mergeError(org.firstinspires.ftc.teamcode.data.protocol.ProtocolError value) {
      copyOnWrite();
      instance.mergeError(value);
      return this;
    }
    /**
     * <code>.ftc.robotdata.v2.ProtocolError error = 19;</code>
     */
    public Builder clearError() {
      copyOnWrite();
      instance.clearError();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:ftc.robotdata.v2.Envelope)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new org.firstinspires.ftc.teamcode.data.protocol.Envelope();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "body_",
            "bodyCase_",
            "protocolVersion_",
            "sessionId_",
            "connectionId_",
            "connectionSequence_",
            "robotElapsedNs_",
            org.firstinspires.ftc.teamcode.data.protocol.Hello.class,
            org.firstinspires.ftc.teamcode.data.protocol.HelloAck.class,
            org.firstinspires.ftc.teamcode.data.protocol.Schema.class,
            org.firstinspires.ftc.teamcode.data.protocol.SampleBatch.class,
            org.firstinspires.ftc.teamcode.data.protocol.Event.class,
            org.firstinspires.ftc.teamcode.data.protocol.Heartbeat.class,
            org.firstinspires.ftc.teamcode.data.protocol.Gap.class,
            org.firstinspires.ftc.teamcode.data.protocol.SessionEnd.class,
            org.firstinspires.ftc.teamcode.data.protocol.GamepadSnapshot.class,
            org.firstinspires.ftc.teamcode.data.protocol.ProtocolError.class,
          };
          java.lang.String info =
              "\u0000\u000f\u0001\u0000\u0001\u0013\u000f\u0000\u0000\u0000\u0001\u000b\u0002\n" +
              "\u0003\n\u0004\u0003\u0005\u0003\n<\u0000\u000b<\u0000\f<\u0000\r<\u0000\u000e<\u0000" +
              "\u000f<\u0000\u0010<\u0000\u0011<\u0000\u0012<\u0000\u0013<\u0000";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<org.firstinspires.ftc.teamcode.data.protocol.Envelope> parser = PARSER;
        if (parser == null) {
          synchronized (org.firstinspires.ftc.teamcode.data.protocol.Envelope.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<org.firstinspires.ftc.teamcode.data.protocol.Envelope>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:ftc.robotdata.v2.Envelope)
  private static final org.firstinspires.ftc.teamcode.data.protocol.Envelope DEFAULT_INSTANCE;
  static {
    Envelope defaultInstance = new Envelope();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      Envelope.class, defaultInstance);
  }

  public static org.firstinspires.ftc.teamcode.data.protocol.Envelope getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<Envelope> PARSER;

  public static com.google.protobuf.Parser<Envelope> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

