// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: robot_data.proto

// Protobuf Java Version: 3.25.5
package org.firstinspires.ftc.teamcode.data.protocol;

public interface EnvelopeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ftc.robotdata.v2.Envelope)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>uint32 protocol_version = 1;</code>
   * @return The protocolVersion.
   */
  int getProtocolVersion();

  /**
   * <pre>
   * 16-byte RFC 4122 UUID
   * </pre>
   *
   * <code>bytes session_id = 2;</code>
   * @return The sessionId.
   */
  com.google.protobuf.ByteString getSessionId();

  /**
   * <pre>
   * 16-byte RFC 4122 UUID
   * </pre>
   *
   * <code>bytes connection_id = 3;</code>
   * @return The connectionId.
   */
  com.google.protobuf.ByteString getConnectionId();

  /**
   * <code>uint64 connection_sequence = 4;</code>
   * @return The connectionSequence.
   */
  long getConnectionSequence();

  /**
   * <code>uint64 robot_elapsed_ns = 5;</code>
   * @return The robotElapsedNs.
   */
  long getRobotElapsedNs();

  /**
   * <code>.ftc.robotdata.v2.Hello hello = 10;</code>
   * @return Whether the hello field is set.
   */
  boolean hasHello();
  /**
   * <code>.ftc.robotdata.v2.Hello hello = 10;</code>
   * @return The hello.
   */
  org.firstinspires.ftc.teamcode.data.protocol.Hello getHello();

  /**
   * <code>.ftc.robotdata.v2.HelloAck hello_ack = 11;</code>
   * @return Whether the helloAck field is set.
   */
  boolean hasHelloAck();
  /**
   * <code>.ftc.robotdata.v2.HelloAck hello_ack = 11;</code>
   * @return The helloAck.
   */
  org.firstinspires.ftc.teamcode.data.protocol.HelloAck getHelloAck();

  /**
   * <code>.ftc.robotdata.v2.Schema schema = 12;</code>
   * @return Whether the schema field is set.
   */
  boolean hasSchema();
  /**
   * <code>.ftc.robotdata.v2.Schema schema = 12;</code>
   * @return The schema.
   */
  org.firstinspires.ftc.teamcode.data.protocol.Schema getSchema();

  /**
   * <code>.ftc.robotdata.v2.SampleBatch sample_batch = 13;</code>
   * @return Whether the sampleBatch field is set.
   */
  boolean hasSampleBatch();
  /**
   * <code>.ftc.robotdata.v2.SampleBatch sample_batch = 13;</code>
   * @return The sampleBatch.
   */
  org.firstinspires.ftc.teamcode.data.protocol.SampleBatch getSampleBatch();

  /**
   * <code>.ftc.robotdata.v2.Event event = 14;</code>
   * @return Whether the event field is set.
   */
  boolean hasEvent();
  /**
   * <code>.ftc.robotdata.v2.Event event = 14;</code>
   * @return The event.
   */
  org.firstinspires.ftc.teamcode.data.protocol.Event getEvent();

  /**
   * <code>.ftc.robotdata.v2.Heartbeat heartbeat = 15;</code>
   * @return Whether the heartbeat field is set.
   */
  boolean hasHeartbeat();
  /**
   * <code>.ftc.robotdata.v2.Heartbeat heartbeat = 15;</code>
   * @return The heartbeat.
   */
  org.firstinspires.ftc.teamcode.data.protocol.Heartbeat getHeartbeat();

  /**
   * <code>.ftc.robotdata.v2.Gap gap = 16;</code>
   * @return Whether the gap field is set.
   */
  boolean hasGap();
  /**
   * <code>.ftc.robotdata.v2.Gap gap = 16;</code>
   * @return The gap.
   */
  org.firstinspires.ftc.teamcode.data.protocol.Gap getGap();

  /**
   * <code>.ftc.robotdata.v2.SessionEnd session_end = 17;</code>
   * @return Whether the sessionEnd field is set.
   */
  boolean hasSessionEnd();
  /**
   * <code>.ftc.robotdata.v2.SessionEnd session_end = 17;</code>
   * @return The sessionEnd.
   */
  org.firstinspires.ftc.teamcode.data.protocol.SessionEnd getSessionEnd();

  /**
   * <code>.ftc.robotdata.v2.GamepadSnapshot gamepad = 18;</code>
   * @return Whether the gamepad field is set.
   */
  boolean hasGamepad();
  /**
   * <code>.ftc.robotdata.v2.GamepadSnapshot gamepad = 18;</code>
   * @return The gamepad.
   */
  org.firstinspires.ftc.teamcode.data.protocol.GamepadSnapshot getGamepad();

  /**
   * <code>.ftc.robotdata.v2.ProtocolError error = 19;</code>
   * @return Whether the error field is set.
   */
  boolean hasError();
  /**
   * <code>.ftc.robotdata.v2.ProtocolError error = 19;</code>
   * @return The error.
   */
  org.firstinspires.ftc.teamcode.data.protocol.ProtocolError getError();

  public org.firstinspires.ftc.teamcode.data.protocol.Envelope.BodyCase getBodyCase();
}
