// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: robot_data.proto

// Protobuf Java Version: 3.25.5
package org.firstinspires.ftc.teamcode.data.protocol;

/**
 * Protobuf type {@code ftc.robotdata.v2.HelloAck}
 */
public  final class HelloAck extends
    com.google.protobuf.GeneratedMessageLite<
        HelloAck, HelloAck.Builder> implements
    // @@protoc_insertion_point(message_implements:ftc.robotdata.v2.HelloAck)
    HelloAckOrBuilder {
  private HelloAck() {
    reason_ = "";
  }
  public static final int ACCEPTED_FIELD_NUMBER = 1;
  private boolean accepted_;
  /**
   * <code>bool accepted = 1;</code>
   * @return The accepted.
   */
  @java.lang.Override
  public boolean getAccepted() {
    return accepted_;
  }
  /**
   * <code>bool accepted = 1;</code>
   * @param value The accepted to set.
   */
  private void setAccepted(boolean value) {
    
    accepted_ = value;
  }
  /**
   * <code>bool accepted = 1;</code>
   */
  private void clearAccepted() {

    accepted_ = false;
  }

  public static final int SERVER_TIME_NS_FIELD_NUMBER = 2;
  private long serverTimeNs_;
  /**
   * <code>uint64 server_time_ns = 2;</code>
   * @return The serverTimeNs.
   */
  @java.lang.Override
  public long getServerTimeNs() {
    return serverTimeNs_;
  }
  /**
   * <code>uint64 server_time_ns = 2;</code>
   * @param value The serverTimeNs to set.
   */
  private void setServerTimeNs(long value) {
    
    serverTimeNs_ = value;
  }
  /**
   * <code>uint64 server_time_ns = 2;</code>
   */
  private void clearServerTimeNs() {

    serverTimeNs_ = 0L;
  }

  public static final int SESSION_RESUMED_FIELD_NUMBER = 3;
  private boolean sessionResumed_;
  /**
   * <code>bool session_resumed = 3;</code>
   * @return The sessionResumed.
   */
  @java.lang.Override
  public boolean getSessionResumed() {
    return sessionResumed_;
  }
  /**
   * <code>bool session_resumed = 3;</code>
   * @param value The sessionResumed to set.
   */
  private void setSessionResumed(boolean value) {
    
    sessionResumed_ = value;
  }
  /**
   * <code>bool session_resumed = 3;</code>
   */
  private void clearSessionResumed() {

    sessionResumed_ = false;
  }

  public static final int REASON_FIELD_NUMBER = 4;
  private java.lang.String reason_;
  /**
   * <code>string reason = 4;</code>
   * @return The reason.
   */
  @java.lang.Override
  public java.lang.String getReason() {
    return reason_;
  }
  /**
   * <code>string reason = 4;</code>
   * @return The bytes for reason.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getReasonBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(reason_);
  }
  /**
   * <code>string reason = 4;</code>
   * @param value The reason to set.
   */
  private void setReason(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    reason_ = value;
  }
  /**
   * <code>string reason = 4;</code>
   */
  private void clearReason() {

    reason_ = getDefaultInstance().getReason();
  }
  /**
   * <code>string reason = 4;</code>
   * @param value The bytes for reason to set.
   */
  private void setReasonBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    reason_ = value.toStringUtf8();

  }

  public static org.firstinspires.ftc.teamcode.data.protocol.HelloAck parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static org.firstinspires.ftc.teamcode.data.protocol.HelloAck parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static org.firstinspires.ftc.teamcode.data.protocol.HelloAck parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static org.firstinspires.ftc.teamcode.data.protocol.HelloAck parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static org.firstinspires.ftc.teamcode.data.protocol.HelloAck parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static org.firstinspires.ftc.teamcode.data.protocol.HelloAck parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static org.firstinspires.ftc.teamcode.data.protocol.HelloAck parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static org.firstinspires.ftc.teamcode.data.protocol.HelloAck parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static org.firstinspires.ftc.teamcode.data.protocol.HelloAck parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static org.firstinspires.ftc.teamcode.data.protocol.HelloAck parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static org.firstinspires.ftc.teamcode.data.protocol.HelloAck parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static org.firstinspires.ftc.teamcode.data.protocol.HelloAck parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(org.firstinspires.ftc.teamcode.data.protocol.HelloAck prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code ftc.robotdata.v2.HelloAck}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        org.firstinspires.ftc.teamcode.data.protocol.HelloAck, Builder> implements
      // @@protoc_insertion_point(builder_implements:ftc.robotdata.v2.HelloAck)
      org.firstinspires.ftc.teamcode.data.protocol.HelloAckOrBuilder {
    // Construct using org.firstinspires.ftc.teamcode.data.protocol.HelloAck.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>bool accepted = 1;</code>
     * @return The accepted.
     */
    @java.lang.Override
    public boolean getAccepted() {
      return instance.getAccepted();
    }
    /**
     * <code>bool accepted = 1;</code>
     * @param value The accepted to set.
     * @return This builder for chaining.
     */
    public Builder setAccepted(boolean value) {
      copyOnWrite();
      instance.setAccepted(value);
      return this;
    }
    /**
     * <code>bool accepted = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearAccepted() {
      copyOnWrite();
      instance.clearAccepted();
      return this;
    }

    /**
     * <code>uint64 server_time_ns = 2;</code>
     * @return The serverTimeNs.
     */
    @java.lang.Override
    public long getServerTimeNs() {
      return instance.getServerTimeNs();
    }
    /**
     * <code>uint64 server_time_ns = 2;</code>
     * @param value The serverTimeNs to set.
     * @return This builder for chaining.
     */
    public Builder setServerTimeNs(long value) {
      copyOnWrite();
      instance.setServerTimeNs(value);
      return this;
    }
    /**
     * <code>uint64 server_time_ns = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearServerTimeNs() {
      copyOnWrite();
      instance.clearServerTimeNs();
      return this;
    }

    /**
     * <code>bool session_resumed = 3;</code>
     * @return The sessionResumed.
     */
    @java.lang.Override
    public boolean getSessionResumed() {
      return instance.getSessionResumed();
    }
    /**
     * <code>bool session_resumed = 3;</code>
     * @param value The sessionResumed to set.
     * @return This builder for chaining.
     */
    public Builder setSessionResumed(boolean value) {
      copyOnWrite();
      instance.setSessionResumed(value);
      return this;
    }
    /**
     * <code>bool session_resumed = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearSessionResumed() {
      copyOnWrite();
      instance.clearSessionResumed();
      return this;
    }

    /**
     * <code>string reason = 4;</code>
     * @return The reason.
     */
    @java.lang.Override
    public java.lang.String getReason() {
      return instance.getReason();
    }
    /**
     * <code>string reason = 4;</code>
     * @return The bytes for reason.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getReasonBytes() {
      return instance.getReasonBytes();
    }
    /**
     * <code>string reason = 4;</code>
     * @param value The reason to set.
     * @return This builder for chaining.
     */
    public Builder setReason(
        java.lang.String value) {
      copyOnWrite();
      instance.setReason(value);
      return this;
    }
    /**
     * <code>string reason = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearReason() {
      copyOnWrite();
      instance.clearReason();
      return this;
    }
    /**
     * <code>string reason = 4;</code>
     * @param value The bytes for reason to set.
     * @return This builder for chaining.
     */
    public Builder setReasonBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setReasonBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:ftc.robotdata.v2.HelloAck)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new org.firstinspires.ftc.teamcode.data.protocol.HelloAck();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "accepted_",
            "serverTimeNs_",
            "sessionResumed_",
            "reason_",
          };
          java.lang.String info =
              "\u0000\u0004\u0000\u0000\u0001\u0004\u0004\u0000\u0000\u0000\u0001\u0007\u0002\u0003" +
              "\u0003\u0007\u0004\u0208";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<org.firstinspires.ftc.teamcode.data.protocol.HelloAck> parser = PARSER;
        if (parser == null) {
          synchronized (org.firstinspires.ftc.teamcode.data.protocol.HelloAck.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<org.firstinspires.ftc.teamcode.data.protocol.HelloAck>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:ftc.robotdata.v2.HelloAck)
  private static final org.firstinspires.ftc.teamcode.data.protocol.HelloAck DEFAULT_INSTANCE;
  static {
    HelloAck defaultInstance = new HelloAck();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      HelloAck.class, defaultInstance);
  }

  public static org.firstinspires.ftc.teamcode.data.protocol.HelloAck getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<HelloAck> PARSER;

  public static com.google.protobuf.Parser<HelloAck> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

