// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: robot_data.proto

// Protobuf Java Version: 3.25.5
package org.firstinspires.ftc.teamcode.data.protocol;

public interface HelloAckOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ftc.robotdata.v2.HelloAck)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>bool accepted = 1;</code>
   * @return The accepted.
   */
  boolean getAccepted();

  /**
   * <code>uint64 server_time_ns = 2;</code>
   * @return The serverTimeNs.
   */
  long getServerTimeNs();

  /**
   * <code>bool session_resumed = 3;</code>
   * @return The sessionResumed.
   */
  boolean getSessionResumed();

  /**
   * <code>string reason = 4;</code>
   * @return The reason.
   */
  java.lang.String getReason();
  /**
   * <code>string reason = 4;</code>
   * @return The bytes for reason.
   */
  com.google.protobuf.ByteString
      getReasonBytes();
}
